name: TDS Week0

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 24f2001637@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Finish
        run: echo "Workflow completed"
